version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=adam
      - MARIADB_DATABASE=wedding
      - MARIADB_PASSWORD=LetsGoDABABY7

  myapp:
    tty: true
    image: docker.io/bitnami/laravel:latest
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=adam
      - DB_DATABASE=wedding
      - DB_PASSWORD=LetsGoDABABY7
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    # privileged: true # Privileged mode could be required to run this container under Windows
